server:
  port: 8080
  servlet:
    context-path: /app

spring:
#server.servlet.context-path=/app
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 03c6d039-a745-406c-85f7-76ee2ee00f50
            client-secret: 08a7092e-3cac-4833-9ac9-240112dd04e3
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: spring-boot3-2025
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/051b2f62-41c5-46d7-9949-540d1a7c9c0e/v2.0
            #https://login.microsoftonline.com/051b2f62-41c5-46d7-9949-540d1a7c9c0e/v2.0/.well-known/openid-configuration
            #https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc
#            authorization-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: name