server:
  port: 8080
  servlet:
    context-path: /app

spring:
  #server.servlet.context-path=/app
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - openid
              - phone
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: AWS Cognito
        provider:
          cognito:
            issuer-uri: ${ISSUER_URI}
            user-name-attribute: username
            #https://login.microsoftonline.com/051b2f62-41c5-46d7-9949-540d1a7c9c0e/v2.0/.well-known/openid-configuration
            #https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc
#            authorization-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: name
logging:
  level:
    org.springframework.security: DEBUG